New code question: Developed for evaluation of the solution
socialsoftware/quizzes-tutor pull request #267
Opened 2021-01-18 21:16 UTC by reganha

Changes:
- Introduces a new code question (Order Question)

2021-02-01 19:06 UTC, ritosilva requested changes
backend reviewed

2021-02-01 19:06 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/tutor/question/service/CreateQuestionTest.groovy
> +
There is several code that is repeated between tests - create auxiliary methods to be reused in the tests

2021-02-05 00:10 UTC, reganha commented on backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/tutor/answer/domain/CodeOrderAnswer.java
> +    public CodeOrderAnswer() {
This is necessary yes. 
It is because of @Entity, it needs an empty constructor, so since another more "complex" is implemented we need this one.

2021-02-05 00:10 UTC, reganha commented on backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/tutor/question/domain/CodeOrderQuestion.java
> +        if (codeOrderSlots.stream().filter(x -> x.getOrder() != null).count() < 3 ){
The idea here is having options that are not used in the final answer.
The usage of these types of slots is recommended in these questions to challenge the students and "confuse".

2021-02-18 10:22 UTC, ritosilva commented on backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/tutor/question/domain/CodeOrderQuestion.java
> +    @OneToMany(cascade = CascadeType.ALL, mappedBy = "questionDetails", fetch = FetchType.LAZY, orphanRemoval = true)
The impact may be in performance. It will be evaluated globally with the other dependencies.

2021-02-18 10:22 UTC, ritosilva commented on backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/tutor/statement/domain/CodeOrderSlotAnswerItem.java
> +    private Integer slotId;
Done!

2021-02-18 10:23 UTC, ritosilva commented on backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/tutor/statement/domain/CodeOrderAnswerItem.java
> +        // TODO: Need to create a string representation for export
Done!

2021-02-23 10:24 UTC, merged